import { portfolio as p } from './data.js';
import './styles.css';
import './backend.css';

const routes = ['home','about','skills','projects','experience','education','certifications','achievements','resume','contact'];
const icon = (x) => `<span class="icon" aria-hidden="true">${x}</span>`;
const link = (path, label, cls='') => `<a class="${cls}" href="${path}">${label}</a>`;
const social = () => `<div class="socials"><a href="${p.personal.github}" aria-label="GitHub">GH</a><a href="${p.personal.linkedin}" aria-label="LinkedIn">in</a><a href="mailto:${p.personal.email}" aria-label="Email">@</a></div>`;
const eyebrow = (text) => `<p class="eyebrow"><i></i>${text}</p>`;
const photo = (large=false) => `<div class="photo-shell ${large?'photo-large':''}"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="hud-label">AI PROFILE <b>● ONLINE</b></div><img src="${p.personal.photo}" alt="Profile placeholder — replace with ${p.personal.name}'s photo" /><span class="corner c1"></span><span class="corner c2"></span></div>`;
function nav(){return `<header><a class="brand" href="/"><span>${p.personal.initials}</span><em>PORTFOLIO</em></a><button class="menu-btn" aria-label="Open navigation" aria-expanded="false">☰</button><nav>${routes.map(r=>`<a href="/${r==='home'?'':r}" data-route="${r}">${r}</a>`).join('')}<a class="resume-nav" href="/resume">Resume ↗</a></nav></header>`}
const pageHead=(tag,title,desc)=>`<section class="page-head wrap">${eyebrow(tag)}<h1>${title}</h1><p>${desc}</p></section>`;
function home(){return `<main class="home"><section class="hero wrap"><div class="hero-copy">${eyebrow('SYSTEM ONLINE · 26.901')}<h1>Hi, I’m <span>${p.personal.name}</span>.</h1><p class="hero-title">${p.personal.title}</p><p class="lede">${p.personal.tagline}</p><p class="typing"><b>&gt; </b><span id="typed">Full Stack Developer</span><i></i></p><div class="actions">${link('/projects','View projects','button primary magnetic')}${link('/contact','Contact me','button ghost magnetic')}</div>${social()}</div><div class="hero-visual">${photo(true)}<div class="hero-code">// DEVELOPER_MODE<br><strong>CREATIVE · CURIOUS · READY</strong></div></div></section><section class="stats wrap">${p.stats.map(s=>`<div class="stat"><strong data-count="${s.value}">${s.value}</strong><span>${s.label}</span></div>`).join('')}</section><section class="split-section wrap"><div>${eyebrow('01 · SIGNAL')}<h2>A human lens<br>on <span>intelligent systems.</span></h2></div><div><p>${p.personal.bio}</p>${link('/about','More about me →','text-link')}</div></section><section class="featured wrap">${eyebrow('SELECTED WORK')}<div class="section-row"><h2>Featured projects</h2>${link('/projects','Explore archive →','text-link')}</div><div class="project-grid">${p.projects.filter(x=>x.featured).map(projectCard).join('')}</div></section></main>`}
function projectCard(x){return `<article class="project-card tilt"><div class="project-art"><span>${x.category}</span><b>${x.name.split(' ').map(w=>w[0]).join('')}</b><i></i></div><div class="project-body"><small>${x.year} · ${x.problem}</small><h3>${x.name}</h3><p>${x.desc}</p><div class="chips">${x.stack.map(t=>`<span>${t}</span>`).join('')}</div><a href="/projects/${x.slug}" class="project-link">View case study <b>↗</b></a></div></article>`}
function about(){return `<main>${pageHead('02 · ABOUT','Building with intent, not just momentum.','A developer journey informed by curiosity, empathy, and a love for solving useful problems.')}<section class="about-intro wrap">${photo()}<div><h2>${p.personal.name}</h2><p>${p.personal.bio}</p><p>${p.personal.learning}</p><div class="terminal">$ cat developer-philosophy.txt<br><strong>Make it clear. Make it useful. Keep learning.</strong></div></div></section><section class="wrap journey"><h2>Journey.log</h2>${p.journey.map(x=>`<article><time>${x.year}</time><div><h3>${x.title}</h3><p>${x.text}</p></div></article>`).join('')}</section></main>`}
function skills(){const groups=[...new Set(p.skills.map(x=>x.group))];return `<main>${pageHead('03 · CAPABILITIES','A focused, evolving toolkit.','Skills are intentional placeholders—edit the central data file to accurately reflect your experience.')}<section class="wrap skill-groups">${groups.map(g=>`<div class="skill-group"><h2>${g}</h2><div class="skill-grid">${p.skills.filter(s=>s.group===g).map(s=>`<article class="skill-card"><div>${icon('◈')}<h3>${s.name}</h3><b>${s.level}%</b></div><p>${s.desc}</p><span class="meter"><i style="--level:${s.level}%"></i></span></article>`).join('')}</div></div>`).join('')}</section></main>`}
function projects(){return `<main>${pageHead('04 · PROJECT ARCHIVE','Things I’ve designed to move ideas forward.','Sample projects show the layout. Replace their details, images, and links in src/data.js.')}<section class="wrap"><div class="filterbar"><div>${['All','Web','AI','Automation','Other'].map((x,i)=>`<button class="filter ${i?'':'active'}" data-filter="${x}">${x}</button>`).join('')}</div><input id="project-search" aria-label="Search projects" placeholder="Search project archive" /></div><div class="project-grid all-projects">${p.projects.map(projectCard).join('')}</div></section></main>`}
function detail(slug){const x=p.projects.find(x=>x.slug===slug)||p.projects[0];return `<main>${pageHead('PROJECT · '+x.category,x.name,x.desc)}<section class="wrap detail-grid"><div><div class="detail-art"><span>CASE STUDY</span><b>${x.name}</b></div><div class="actions">${link('#','GitHub ↗','button ghost')}${link('#','Live demo ↗','button primary')}</div></div><div class="case-copy"><h2>Overview</h2><p>${x.desc} This is deliberately sample content. Edit the project object in the central data file to add an honest account of your work.</p><h2>Problem</h2><p>${x.problem}. Explain the context and why solving it mattered.</p><h2>Solution</h2><p>Describe your approach, key features, challenges, what you learned, and future improvements here.</p><div class="chips">${x.stack.map(t=>`<span>${t}</span>`).join('')}</div></div></section></main>`}
function timelinePage(type,title,desc,data,render){return `<main>${pageHead(type,title,desc)}<section class="wrap timelines">${data.map(render).join('')}</section></main>`}
function experience(){return timelinePage('05 · EXPERIENCE','Learning in public, building in teams.','Use this space for internships, freelance work, technical clubs, hackathons, and meaningful collaboration.',p.experience,x=>`<article class="timeline-card"><small>${x.duration}</small><h2>${x.role}</h2><h3>${x.org}</h3><ul>${x.bullets.map(b=>`<li>${b}</li>`).join('')}</ul><div class="chips">${x.tech.map(t=>`<span>${t}</span>`).join('')}</div></article>`)}
function education(){return timelinePage('06 · EDUCATION','Foundations for what comes next.','Keep education concise, relevant, and grounded in your actual experience.',p.education,x=>`<article class="timeline-card"><small>${x.duration}</small><h2>${x.institution}</h2><h3>${x.course}</h3><p><b>Relevant:</b> ${x.subjects.join(' · ')}</p><p>${x.activities}</p></article>`)}
function certs(){return `<main>${pageHead('07 · CREDENTIALS','Evidence of deliberate learning.','Add verified certificate links and images when you have them.')}<section class="wrap certificate-grid">${p.certifications.map((x,i)=>`<article class="certificate"><div>${icon(i?'✦':'⌁')}</div><small>${x.category}</small><h2>${x.name}</h2><p>${x.issuer}</p><footer><span>${x.date}</span><button>Verify ↗</button></footer><code>${x.id}</code></article>`).join('')}</section></main>`}
function achievements(){return `<main>${pageHead('08 · MILESTONES','Progress, measured in moments.','A place for the work you are proud to put your name beside.')}<section class="wrap achievement-grid">${p.achievements.map((x,i)=>`<article class="achievement"><b>0${i+1}</b><small>${x.type}</small><h2>${x.title}</h2><p>${x.desc}</p></article>`).join('')}</section></main>`}
function resume(){return `<main class="resume-page">${pageHead('09 · RESUME','A concise signal of how I work.','This printable profile is generated from your central portfolio data.')}<section class="wrap resume-sheet"><div class="resume-top"><div><h2>${p.personal.name}</h2><p>${p.personal.title}</p></div>${photo()}</div><h3>Summary</h3><p>${p.personal.bio}</p><h3>Core skills</h3><p>${p.skills.map(x=>x.name).join(' · ')}</p><h3>Projects</h3>${p.projects.map(x=>`<p><b>${x.name}</b> — ${x.desc}</p>`).join('')}<h3>Education</h3>${p.education.map(x=>`<p><b>${x.course}</b>, ${x.institution} (${x.duration})</p>`).join('')}<button class="button primary print" onclick="window.print()">Print / save as PDF</button></section></main>`}
function contact(){return `<main>${pageHead('10 · CONTACT','Let’s make something useful.','For opportunities, collaborations, or a good technical conversation—send a signal.')}<section class="wrap contact-grid"><div><h2>Direct channel</h2><a class="contact-email" href="mailto:${p.personal.email}">${p.personal.email}</a><p>${p.personal.location}</p>${social()}<div class="terminal">&gt; STATUS: OPEN TO CONVERSATION<br><strong>Response time: [YOUR PREFERENCE]</strong></div></div><form id="contact-form" novalidate><label>Name<input required name="name" minlength="2" maxlength="100" placeholder="Your name" /></label><label>Email<input required type="email" name="email" maxlength="254" placeholder="you@example.com" /></label><label>Subject<input required name="subject" minlength="3" maxlength="160" placeholder="What’s on your mind?" /></label><label>Message<textarea required name="message" minlength="10" maxlength="5000" rows="5" placeholder="Write your message..."></textarea></label><input class="honeypot" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true" /><button class="button primary magnetic" type="submit">Send message ↗</button><p class="form-msg" aria-live="polite"></p></form></section></main>`}
function footer(){return `<footer class="site-footer"><div class="wrap"><span>© 2026 ${p.personal.name}. All rights reserved.</span><span class="online">● SYSTEM ONLINE</span><span>Designed & built with intent.</span></div></footer>`}
function render(){let path=location.pathname.replace(/^\//,'')||'home'; let html;if(path.startsWith('projects/'))html=detail(path.split('/')[1]);else {const pages={home,about,skills,projects,experience,education,certifications:certs,achievements,resume,contact};html=(pages[path]||home)()} document.title=`${path==='home'?p.personal.name:path.replace(/\b\w/g,c=>c.toUpperCase())} — Portfolio`; document.querySelector('#app').innerHTML=nav()+html+footer()+`<button class="backtop" aria-label="Back to top">↑</button>`;wire();}
function wire(){document.querySelectorAll('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();history.pushState({},'',a.getAttribute('href'));render();scrollTo({top:0,behavior:'smooth'})})); const mb=document.querySelector('.menu-btn'), navEl=document.querySelector('header nav');mb?.addEventListener('click',()=>{navEl.classList.toggle('open');mb.setAttribute('aria-expanded',navEl.classList.contains('open'))});document.querySelector('.backtop').onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.tilt').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`perspective(900px) rotateX(${(e.clientY-r.top-r.height/2)/-18}deg) rotateY(${(e.clientX-r.left-r.width/2)/18}deg) translateY(-6px)`}));document.querySelectorAll('.tilt').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filterProjects(b.dataset.filter)});document.querySelector('#project-search')?.addEventListener('input',e=>filterProjects(document.querySelector('.filter.active').dataset.filter,e.target.value));document.querySelector('#contact-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,msg=f.querySelector('.form-msg'),button=f.querySelector('button[type="submit"]');if(!f.checkValidity()){msg.textContent='Please complete the highlighted fields.';f.reportValidity();return}button.disabled=true;button.textContent='Sending…';msg.textContent='';try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f)))});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to send your message.');msg.textContent=result.message;f.reset()}catch(error){msg.textContent=error.message||'Unable to send your message. Please email me directly.'}finally{button.disabled=false;button.textContent='Send message ↗'}});typing();}
function filterProjects(cat='All',q=''){document.querySelectorAll('.all-projects .project-card').forEach((el,i)=>{let x=p.projects[i],show=(cat==='All'||x.category===cat)&&JSON.stringify(x).toLowerCase().includes(q.toLowerCase());el.hidden=!show})}
function typing(){const el=document.querySelector('#typed');if(!el)return;let words=['Full Stack Developer','AI Enthusiast','Software Developer','Problem Solver','Competitive Programmer'],i=0;setInterval(()=>{i=(i+1)%words.length;el.classList.add('fade');setTimeout(()=>{el.textContent=words[i];el.classList.remove('fade')},180)},2400)}
window.addEventListener('popstate',render);render();
// Lightweight adaptive cyber scene; intentionally pauses off-screen and honors reduced motion.
const canvas=document.querySelector('#cyber-canvas'),ctx=canvas.getContext('2d');let mx=.5,my=.5,particles=[];function size(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);particles=Array.from({length:innerWidth<700?22:54},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,v:Math.random()*.22+.05,r:Math.random()*1.7+.4}))}size();addEventListener('resize',size);addEventListener('pointermove',e=>{mx=e.clientX/innerWidth;my=e.clientY/innerHeight;document.documentElement.style.setProperty('--mx',mx);document.documentElement.style.setProperty('--my',my)});function scene(t){if(document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches){requestAnimationFrame(scene);return}ctx.clearRect(0,0,innerWidth,innerHeight);let w=innerWidth,h=innerHeight;ctx.strokeStyle='rgba(111,255,233,.08)';ctx.lineWidth=1;for(let y=h*.55;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+(y-h*.55)*.18);ctx.stroke()}for(let x=0;x<w;x+=56){ctx.beginPath();ctx.moveTo(w*.5+(x-w*.5)*.2,h*.55);ctx.lineTo(x,h);ctx.stroke()}particles.forEach((a,i)=>{a.y-=a.v;if(a.y<0)a.y=h;let dx=a.x-mx*w,dy=a.y-my*h;if(Math.hypot(dx,dy)<150){ctx.strokeStyle='rgba(119,143,255,.16)';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(mx*w,my*h);ctx.stroke()}ctx.fillStyle='rgba(111,255,233,.65)';ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,7);ctx.fill()});let cx=w*.78+(mx-.5)*20,cy=h*.32+(my-.5)*12,s=Math.min(w,h)*.17;ctx.strokeStyle='rgba(110,151,255,.18)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(cx,cy,s*.74,s,0,0,7);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-s*.48,cy+s*.25);ctx.quadraticCurveTo(cx,cy+s*.65,cx+s*.48,cy+s*.25);ctx.stroke();ctx.fillStyle='rgba(111,255,233,.4)';[-.24,.24].forEach(k=>{ctx.beginPath();ctx.arc(cx+s*k,cy-s*.12,3,0,7);ctx.fill()});requestAnimationFrame(scene)}requestAnimationFrame(scene);
if(matchMedia('(pointer:fine)').matches){let d=document.querySelector('#cursor-dot'),r=document.querySelector('#cursor-ring');addEventListener('pointermove',e=>{d.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;r.style.transform=`translate(${e.clientX}px,${e.clientY}px)`});document.addEventListener('pointerover',e=>{if(e.target.closest('a,button,input,textarea'))r.classList.add('active')});document.addEventListener('pointerout',()=>r.classList.remove('active'))}
